version: '3.8'

services:
  # RPi5 dla rzeczywistego sprzętu RPi3
  rpi:
    build: ./rpi-emulator
    container_name: c20-rpi
    privileged: true
    volumes:
      - ./shared:/shared
      - /dev:/dev
    networks:
      - c20-network
    environment:
      - MQTT_BROKER=mosquitto
      - SYSTEM_MODE=C20
      - HARDWARE_MODE=true
    depends_on:
      - mosquitto
    profiles:
      - hardware

  # RPi5 emulator dla PC z emulowanymi portami
  rpi3pc:
    build: ./rpi-emulator
    container_name: c20-rpi3pc
    ports:
      - "4000:4000"  # API port
    volumes:
      - ./shared:/shared
      - i2c-bus:/dev/i2c
    networks:
      - c20-network
    environment:
      - MQTT_BROKER=mosquitto
      - SYSTEM_MODE=C20
      - GPIO_MOCK=true
      - I2C_MOCK=true
      - EMULATION_MODE=true
    depends_on:
      - mosquitto

  # LCD Display (7.9" HDMI)
  lcd-display:
    build: ./lcd-display
    container_name: c20-lcd
    ports:
      - "8089:80"
    networks:
      - c20-network
    environment:
      - WS_URL=ws://rpi3pc:9001
    depends_on:
      - rpi3pc

  # HUI Keyboard Panel
  hui-keyboard:
    build: ./hui-keyboard
    container_name: c20-keyboard
    ports:
      - "8087:80"
    networks:
      - c20-network
    environment:
      - RPI_HOST=rpi3pc
      - I2C_ADDRESS=0x20
    depends_on:
      - rpi3pc

  # Symulacja czujników ciśnienia
  pressure-sensors:
    build: ./pressure-sensors
    container_name: c20-sensors
    volumes:
      - i2c-bus:/dev/i2c
    networks:
      - c20-network
    environment:
      - I2C_BUS=1
      - SENSOR_LP_ADDR=0x48
      - SENSOR_MP_ADDR=0x49
      - SENSOR_HP_ADDR=0x4A

  # PCB OUT 12 - Sterownik zaworów
  valve-controller:
    build: ./valve-controller
    container_name: c20-valves
    volumes:
      - i2c-bus:/dev/i2c
    networks:
      - c20-network
    environment:
      - I2C_ADDRESS=0x21
      - NUM_OUTPUTS=12

  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: c20-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - c20-network

  # WebGUI na porcie 8088
  webgui:
    build: ./frontend
    container_name: c20-webgui
    ports:
      - "8088:80"
    networks:
      - c20-network
    environment:
      - API_URL=http://localhost:4000
    depends_on:
      - rpi3pc


  # Symulator Modbus RTU IO 8CH
  modbus-io-8ch:
    build: ./modbus-io-8ch
    container_name: c20-modbus-io
    ports:
      - "5020:5020"  # TCP bridge dla Modbus RTU
      - "8085:8085"  # Web API
    volumes:
      - modbus-rtu:/dev/modbus
    networks:
      - c20-network
    environment:
      - DEVICE_ADDRESS=1
      - BAUDRATE=9600
      - WEB_PORT=8085

  # Wizualizacja Modbus
  modbus-visualizer:
    build: ./modbus-visualizer
    container_name: c20-modbus-viz
    ports:
      - "8084:80"
    networks:
      - c20-network
    environment:
      - MODBUS_API=http://localhost:8085
    depends_on:
      - modbus-io-8ch


networks:
  c20-network:
    driver: bridge

volumes:
  modbus-rtu:
  i2c-bus: