version: '3.8'

services:
  rpi-emulator:
    build: ./rpi-emulator
    container_name: rpi-emulator
    restart: unless-stopped
    volumes:
      - ./shared:/app/shared
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - iot-network

  lcd-display:
    build: ./lcd-display
    container_name: lcd-display
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - iot-network
    depends_on:
      - rpi-emulator

  hui-keyboard:
    build: ./hui-keyboard
    container_name: hui-keyboard
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - iot-network
    depends_on:
      - rpi-emulator

  pressure-sensors:
    build: ./pressure-sensors
    container_name: pressure-sensors
    restart: unless-stopped
    volumes:
      - ./shared:/app/shared
    networks:
      - iot-network
    depends_on:
      - rpi-emulator

  valve-controller:
    build: ./valve-controller
    container_name: valve-controller
    restart: unless-stopped
    volumes:
      - ./shared:/app/shared
    networks:
      - iot-network
    depends_on:
      - rpi-emulator

  test-procedures:
    build: ./test-procedures
    container_name: test-procedures
    restart: unless-stopped
    volumes:
      - ./shared:/app/shared
    networks:
      - iot-network
    depends_on:
      - rpi-emulator

networks:
  iot-network:
    driver: bridge
